Feature : Add prayer times with dynamic location
kareemabdeen/QuranyApp pull request #13
Opened 2024-08-10 21:48 UTC by AyaNady17

2024-08-11 10:59 UTC, kareemabdeen requested changes

2024-08-11 10:59 UTC, kareemabdeen commented on lib/Features/PrayerTimes/view/prayer_times_screen.dart
> +      child: Directionality(
For what Directionality used here?

2024-08-11 10:59 UTC, kareemabdeen commented on lib/Features/PrayerTimes/view/prayer_times_screen.dart
> +import 'package:flutter/material.dart';
- Name it as  PrayerTimesPage widget to match the Naming style of all project. 

- Extract the body of the PrayerTimesPage into a separate widget and name it WidgetnameViewBlocBuilder.

- Access FormatDate from PrayerTimesCubit or create it in **core/Functions**

2024-08-11 20:39 UTC, AyaNady17 commented on lib/Features/PrayerTimes/view/prayer_times_screen.dart
> +import 'package:flutter/material.dart';
done

2024-08-13 13:37 UTC, kareemabdeen approved these changes

2024-08-13 19:08 UTC, merged